### ISSUE TITLE
Progress of Missing features.

### ISSUE THREAD

**Issue by littleboy62** [damien122/Autoit-Visual-Studio-Extension#1]
Hello everyone.

First, sorry for potential mistakes, I'm French.

I wish to know progress of missing features, from autoit extension, these : 

> Missing Features
> 
>  run build
>   compile build

I use Scite for autoit, for the moment

But I appreciate your extension
I'm looking forward to use it or test it.

Ah... If you want, i can test it. :)

Anyway, great job, really.
Carry on.

Cheers.
Thomas

**Comment by damien122** [comment]
Hi,

thanks for your feedback.

Sorry to disapoint you but I will not work on this project any more, because I have moved to Mac and I don't use AutoIt any more.
So if you want this features, feal free to fork this project or I can add you to my project :)

Regards,
Damien
