### ISSUE TITLE
Further Development

### ISSUE THREAD

**Issue by loganch** [damien122/Autoit-Visual-Studio-Extension#2]
Hello, I've forked your repo and managed to get some things like script launching working, but saw that you're no longer working on this. I've started setting up to publish this on the Marketplace separately but first wanted to know if you'd be interested in either doing pull requests and throwing it up or adding rights for me to upload and make changes to the existing extension as seen at [this link](https://github.com/Microsoft/vscode/issues/3670#issuecomment-200277260).

**Comment by damien122** [comment]
Hi, nice to hear about your work. 
I had tryed to manage the rights at the the market place but unfortunattely I can't find the place where to do it ... I can make you the owner of this project. Is this ok for you?

**Comment by loganch** [comment]
Yes, that should work. Thanks!

**Comment by damien122** [comment]
can you explain me pls. where to find the option to change the owner?

**Comment by loganch** [comment]
Sure, go to https://marketplace.visualstudio.com/manage, click on the publisher name (Damien) in bold text up top. In the drop-down, click on 'Edit publisher...' and in the pop-up window that appears, click on 'Roles' and then 'Add'. Enter my e-mail, losesmc@gmail.com as the address and set the role as 'Owner', then click 'Add'.

**Comment by damien122** [comment]
ok thx ... done ... you are now an owner and you should release new versions. If you have some problems just let me know.

**Comment by loganch** [comment]
Yep, I see it in my Marketplace management window. Thanks for your help.
