### ISSUE TITLE
Improvement: Jump to function and back (Go to definition/implementation)

### ISSUE THREAD

**Issue by sven-seyfert** [damien122/Autoit-Visual-Studio-Extension#3]
### *Hi and thanks a lot for this great extension!*

I use since many years the **SciTE Editor** for AutoIt scripts. Now I use **VSCode** for the implementation and I love it. But it's not possible to use the 
> Go to Definition

or

> Go to implementation

functionality within your extension.

Is it possible to create this feature like in SciTE called **Jump to function** and **Jump back**? It would be very helpful and handy. I hope it clear what I mean and I'm very grateful for each feedback :) .

    With kind regards
    Sven Seyfert

**Comment by loganch** [comment]
Hello, I think you may have meant to post this in over at https://github.com/loganch/AutoIt-VSCode, where I've taken over maintaining the extension. If you're updated to the latest version, you should be able to use Ctrl+Shift+O to bring up the symbols within the document, and highlighting a function should take you to the location that a function was defined within the script.

**Comment by sven-seyfert** [comment]
### *Hi loganch,*

that's great. I didn't know about this but I tryed and like it much. I notice that the shortcut

> Ctrl + Shift + O

and then

> @:

even **sorted** to functions and variables - perfect! Thanks a lot for this hint. You can close the issue and for the next improvements I will use [loganch/AutoIt-VSCode](https://github.com/loganch/AutoIt-VSCode).

    With kind regards
    Sven Seyfert
