### ISSUE TITLE
License agreement

### ISSUE THREAD

**Issue by grackov** [damien122/Autoit-Visual-Studio-Extension#4]
Please provide a License agreement in which this software adheres to.

**Comment by loganch** [comment]
Hello @grackov, the extension is no longer being maintained on this repository, I've taken over developing/publishing at https://github.com/loganch/AutoIt-VSCode.

**Comment by damien122** [comment]
@loganch by the way ... you did a great job as I can see :+1: 
I will close this Issue here.
@grackov you can open a new one in the repo from @loganch.
